/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import App.Main;
import javax.swing.ImageIcon;

/**
 *
 * @author franc
 */
public class HelpMenu extends javax.swing.JFrame {

    /**
     * Creates new form AccueilFrame
     */
    public HelpMenu() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        nextPage5 = new javax.swing.JButton();
        prec5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnBack4 = new javax.swing.JButton();
        nextPage4 = new javax.swing.JButton();
        prec4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBack3 = new javax.swing.JButton();
        nextPage3 = new javax.swing.JButton();
        prec3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JButton();
        nextPage1 = new javax.swing.JButton();
        prec2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nextPage = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnBack8 = new javax.swing.JButton();
        nextPage8 = new javax.swing.JButton();
        prec8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack6 = new javax.swing.JButton();
        nextPage6 = new javax.swing.JButton();
        prec6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBack7 = new javax.swing.JButton();
        nextPage7 = new javax.swing.JButton();
        prec7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnBack9 = new javax.swing.JButton();
        nextPage9 = new javax.swing.JButton();
        prec9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnBack10 = new javax.swing.JButton();
        nextPage10 = new javax.swing.JButton();
        prec10 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnBack11 = new javax.swing.JButton();
        prec11 = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/commencer.gif"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 600, 410));

        jLabel30.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Ou chargez une partie sauvegardée");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel29.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Commencez une nouvelle partie");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Maintenant allons apprendre à jouer ! ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        btnBack5.setBackground(new java.awt.Color(0, 153, 153));
        btnBack5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack5.setForeground(new java.awt.Color(255, 255, 255));
        btnBack5.setText("< retour A l'accueil");
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage5.setBackground(new java.awt.Color(0, 153, 153));
        nextPage5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage5.setForeground(new java.awt.Color(255, 255, 255));
        nextPage5.setText("Page suivante >");
        nextPage5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage5ActionPerformed(evt);
            }
        });
        jPanel5.add(nextPage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec5.setBackground(new java.awt.Color(0, 153, 153));
        prec5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec5.setForeground(new java.awt.Color(255, 255, 255));
        prec5.setText("< page precedente");
        prec5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec5ActionPerformed(evt);
            }
        });
        jPanel5.add(prec5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack4.setBackground(new java.awt.Color(0, 153, 153));
        btnBack4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack4.setForeground(new java.awt.Color(255, 255, 255));
        btnBack4.setText("< retour A l'accueil");
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage4.setBackground(new java.awt.Color(0, 153, 153));
        nextPage4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage4.setForeground(new java.awt.Color(255, 255, 255));
        nextPage4.setText("Page suivante >");
        nextPage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage4ActionPerformed(evt);
            }
        });
        jPanel4.add(nextPage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec4.setBackground(new java.awt.Color(0, 153, 153));
        prec4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec4.setForeground(new java.awt.Color(255, 255, 255));
        prec4.setText("< page precedente");
        prec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec4ActionPerformed(evt);
            }
        });
        jPanel4.add(prec4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page4.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack3.setBackground(new java.awt.Color(0, 153, 153));
        btnBack3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(255, 255, 255));
        btnBack3.setText("< retour A l'accueil");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        nextPage3.setBackground(new java.awt.Color(0, 153, 153));
        nextPage3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage3.setForeground(new java.awt.Color(255, 255, 255));
        nextPage3.setText("Page suivante >");
        nextPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage3ActionPerformed(evt);
            }
        });
        jPanel3.add(nextPage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 160, 30));

        prec3.setBackground(new java.awt.Color(0, 153, 153));
        prec3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec3.setForeground(new java.awt.Color(255, 255, 255));
        prec3.setText("< page precedente");
        prec3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec3ActionPerformed(evt);
            }
        });
        jPanel3.add(prec3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page3.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack2.setBackground(new java.awt.Color(0, 153, 153));
        btnBack2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("< retour A l'accueil");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage1.setBackground(new java.awt.Color(0, 153, 153));
        nextPage1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage1.setForeground(new java.awt.Color(255, 255, 255));
        nextPage1.setText("Page suivante >");
        nextPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage1ActionPerformed(evt);
            }
        });
        jPanel2.add(nextPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 160, 30));

        prec2.setBackground(new java.awt.Color(0, 153, 153));
        prec2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec2.setForeground(new java.awt.Color(255, 255, 255));
        prec2.setText("< page precedente");
        prec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec2ActionPerformed(evt);
            }
        });
        jPanel2.add(prec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page2.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextPage.setBackground(new java.awt.Color(0, 153, 153));
        nextPage.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage.setForeground(new java.awt.Color(255, 255, 255));
        nextPage.setText("Page suivante >");
        nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageActionPerformed(evt);
            }
        });
        jPanel1.add(nextPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 160, 30));

        btnBack1.setBackground(new java.awt.Color(0, 153, 153));
        btnBack1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("< retour A l'accueil");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deplacer.gif"))); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 620, 360));

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Quand le joueur2 fini on passe au tour suivant");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel28.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Pas de soucis! Sauvegardez votre partie et revenez la charger à tout moment");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        jLabel25.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Déplacez vos unités tant que vous avez des points de déplacements");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Passer la main quand vous avez fini");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Vous voulez prendre une pause ?");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        btnBack8.setBackground(new java.awt.Color(0, 153, 153));
        btnBack8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack8.setForeground(new java.awt.Color(255, 255, 255));
        btnBack8.setText("< retour A l'accueil");
        btnBack8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack8ActionPerformed(evt);
            }
        });
        jPanel8.add(btnBack8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage8.setBackground(new java.awt.Color(0, 153, 153));
        nextPage8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage8.setForeground(new java.awt.Color(255, 255, 255));
        nextPage8.setText("Page suivante >");
        nextPage8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage8ActionPerformed(evt);
            }
        });
        jPanel8.add(nextPage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec8.setBackground(new java.awt.Color(0, 153, 153));
        prec8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec8.setForeground(new java.awt.Color(255, 255, 255));
        prec8.setText("< page precedente");
        prec8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec8ActionPerformed(evt);
            }
        });
        jPanel8.add(prec8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/noms.gif"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 640, 390));

        btnBack6.setBackground(new java.awt.Color(0, 153, 153));
        btnBack6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack6.setForeground(new java.awt.Color(255, 255, 255));
        btnBack6.setText("< retour A l'accueil");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        jPanel6.add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage6.setBackground(new java.awt.Color(0, 153, 153));
        nextPage6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage6.setForeground(new java.awt.Color(255, 255, 255));
        nextPage6.setText("Page suivante >");
        nextPage6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage6ActionPerformed(evt);
            }
        });
        jPanel6.add(nextPage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec6.setBackground(new java.awt.Color(0, 153, 153));
        prec6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec6.setForeground(new java.awt.Color(255, 255, 255));
        prec6.setText("< page precedente");
        prec6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec6ActionPerformed(evt);
            }
        });
        jPanel6.add(prec6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Placez vos unités sur le plateau:");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Maintenant allons apprendre à jouer ! ");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/placer.gif"))); // NOI18N
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 620, 380));

        btnBack7.setBackground(new java.awt.Color(0, 153, 153));
        btnBack7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack7.setForeground(new java.awt.Color(255, 255, 255));
        btnBack7.setText("< retour A l'accueil");
        btnBack7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack7ActionPerformed(evt);
            }
        });
        jPanel7.add(btnBack7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage7.setBackground(new java.awt.Color(0, 153, 153));
        nextPage7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage7.setForeground(new java.awt.Color(255, 255, 255));
        nextPage7.setText("Page suivante >");
        nextPage7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage7ActionPerformed(evt);
            }
        });
        jPanel7.add(nextPage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec7.setBackground(new java.awt.Color(0, 153, 153));
        prec7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec7.setForeground(new java.awt.Color(255, 255, 255));
        prec7.setText("< page precedente");
        prec7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec7ActionPerformed(evt);
            }
        });
        jPanel7.add(prec7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attaquer.gif"))); // NOI18N
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 590, 480));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Attaquez vos adversaire:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        btnBack9.setBackground(new java.awt.Color(0, 153, 153));
        btnBack9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack9.setForeground(new java.awt.Color(255, 255, 255));
        btnBack9.setText("< retour A l'accueil");
        btnBack9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack9ActionPerformed(evt);
            }
        });
        jPanel9.add(btnBack9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage9.setBackground(new java.awt.Color(0, 153, 153));
        nextPage9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage9.setForeground(new java.awt.Color(255, 255, 255));
        nextPage9.setText("Page suivante >");
        nextPage9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage9ActionPerformed(evt);
            }
        });
        jPanel9.add(nextPage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec9.setBackground(new java.awt.Color(0, 153, 153));
        prec9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec9.setForeground(new java.awt.Color(255, 255, 255));
        prec9.setText("< page precedente");
        prec9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec9ActionPerformed(evt);
            }
        });
        jPanel9.add(prec9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attDis.gif"))); // NOI18N
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 720, 410));

        jLabel26.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Attaquez vos ennemis à distance:");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        btnBack10.setBackground(new java.awt.Color(0, 153, 153));
        btnBack10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack10.setForeground(new java.awt.Color(255, 255, 255));
        btnBack10.setText("< retour A l'accueil");
        btnBack10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack10ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBack10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        nextPage10.setBackground(new java.awt.Color(0, 153, 153));
        nextPage10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nextPage10.setForeground(new java.awt.Color(255, 255, 255));
        nextPage10.setText("Page suivante >");
        nextPage10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPage10ActionPerformed(evt);
            }
        });
        jPanel10.add(nextPage10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 165, 30));

        prec10.setBackground(new java.awt.Color(0, 153, 153));
        prec10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec10.setForeground(new java.awt.Color(255, 255, 255));
        prec10.setText("< page precedente");
        prec10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec10ActionPerformed(evt);
            }
        });
        jPanel10.add(prec10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Et voilà vous étes prêt pour commencer !");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        btnBack11.setBackground(new java.awt.Color(0, 153, 153));
        btnBack11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack11.setForeground(new java.awt.Color(255, 255, 255));
        btnBack11.setText(" retour A l'accueil");
        btnBack11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack11ActionPerformed(evt);
            }
        });
        jPanel11.add(btnBack11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, 40));

        prec11.setBackground(new java.awt.Color(0, 153, 153));
        prec11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        prec11.setForeground(new java.awt.Color(255, 255, 255));
        prec11.setText("< page precedente");
        prec11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec11ActionPerformed(evt);
            }
        });
        jPanel11.add(prec11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 30));

        btnNewGame.setBackground(new java.awt.Color(0, 153, 153));
        btnNewGame.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(255, 255, 255));
        btnNewGame.setText("Démarrer la partie");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });
        jPanel11.add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 200, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagebg.png"))); // NOI18N
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        
    }//GEN-LAST:event_nextPageActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void nextPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage1ActionPerformed
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_nextPage1ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void nextPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage3ActionPerformed
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_nextPage3ActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void nextPage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage4ActionPerformed
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_nextPage4ActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void nextPage5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage5ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_nextPage5ActionPerformed

    private void prec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec2ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_prec2ActionPerformed

    private void prec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec3ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_prec3ActionPerformed

    private void prec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec4ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_prec4ActionPerformed

    private void prec5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec5ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_prec5ActionPerformed

    private void btnBack8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack8ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack8ActionPerformed

    private void nextPage8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage8ActionPerformed
        // TODO add your handling code here:
        jPanel8.setVisible(false);
        jPanel9.setVisible(true);
    }//GEN-LAST:event_nextPage8ActionPerformed

    private void prec8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec8ActionPerformed
        // TODO add your handling code here:
        jPanel8.setVisible(false);
        jPanel7.setVisible(true);
    }//GEN-LAST:event_prec8ActionPerformed

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack6ActionPerformed

    private void nextPage6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage6ActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);
    }//GEN-LAST:event_nextPage6ActionPerformed

    private void prec6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec6ActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(false);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_prec6ActionPerformed

    private void btnBack7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack7ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack7ActionPerformed

    private void nextPage7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage7ActionPerformed
        // TODO add your handling code here:
        jPanel7.setVisible(false);
        jPanel8.setVisible(true);
    }//GEN-LAST:event_nextPage7ActionPerformed

    private void prec7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec7ActionPerformed
        // TODO add your handling code here:
        jPanel7.setVisible(false);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_prec7ActionPerformed

    private void btnBack9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack9ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack9ActionPerformed

    private void nextPage9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage9ActionPerformed
        // TODO add your handling code here:
        jPanel9.setVisible(false);
        jPanel10.setVisible(true);
    }//GEN-LAST:event_nextPage9ActionPerformed

    private void prec9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec9ActionPerformed
        // TODO add your handling code here:
        jPanel9.setVisible(false);
        jPanel8.setVisible(true);
    }//GEN-LAST:event_prec9ActionPerformed

    private void btnBack11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack11ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack11ActionPerformed

    private void prec11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec11ActionPerformed
        // TODO add your handling code here:
        jPanel11.setVisible(false);
        jPanel10.setVisible(true);
    }//GEN-LAST:event_prec11ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        PlayersInfoFrame pinfo = new PlayersInfoFrame();
        pinfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnBack10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack10ActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBack10ActionPerformed

    private void nextPage10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPage10ActionPerformed
        // TODO add your handling code here:
        jPanel10.setVisible(false);
        jPanel11.setVisible(true);
    }//GEN-LAST:event_nextPage10ActionPerformed

    private void prec10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec10ActionPerformed
        // TODO add your handling code here:
        jPanel10.setVisible(false);
        jPanel9.setVisible(true);
    }//GEN-LAST:event_prec10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HelpMenu().setVisible(true);
        });
    }

    private javax.swing.JButton nextPage2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack10;
    private javax.swing.JButton btnBack11;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBack5;
    private javax.swing.JButton btnBack6;
    private javax.swing.JButton btnBack7;
    private javax.swing.JButton btnBack8;
    private javax.swing.JButton btnBack9;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton nextPage;
    private javax.swing.JButton nextPage1;
    private javax.swing.JButton nextPage10;
    private javax.swing.JButton nextPage3;
    private javax.swing.JButton nextPage4;
    private javax.swing.JButton nextPage5;
    private javax.swing.JButton nextPage6;
    private javax.swing.JButton nextPage7;
    private javax.swing.JButton nextPage8;
    private javax.swing.JButton nextPage9;
    private javax.swing.JButton prec10;
    private javax.swing.JButton prec11;
    private javax.swing.JButton prec2;
    private javax.swing.JButton prec3;
    private javax.swing.JButton prec4;
    private javax.swing.JButton prec5;
    private javax.swing.JButton prec6;
    private javax.swing.JButton prec7;
    private javax.swing.JButton prec8;
    private javax.swing.JButton prec9;
    // End of variables declaration//GEN-END:variables
}
