package App;

import Controller.Partie;
import View.HelpMenu;
import View.PlateauFrame;
import View.PlayersInfoFrame;
import java.awt.Graphics;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


public class Main extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents ();
        SoundPlayer soundPlayer = new SoundPlayer () ;
        Thread soundThread = new Thread( soundPlayer);
        soundThread.start();
    }
    
    private void setContentPaneWithBackgroundImage(String imagePath) {
        JPanel panel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Image image = new ImageIcon(imagePath).getImage();
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };

        setContentPane(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSubTitle = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnChargerPartie = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEYOND THE RIVER");
        setPreferredSize(new java.awt.Dimension(860, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSubTitle.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        lbSubTitle.setForeground(new java.awt.Color(204, 255, 255));
        lbSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubTitle.setText("WARGAME");
        getContentPane().add(lbSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 150, 30));

        btnNewGame.setBackground(new java.awt.Color(0, 102, 102));
        btnNewGame.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(255, 255, 255));
        btnNewGame.setText("NOUVELLE PARTIE");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 196, 40));

        btnExit.setBackground(new java.awt.Color(0, 102, 102));
        btnExit.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("qUITTER LA PARTIE");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 368, 196, 40));

        btnHelp.setBackground(new java.awt.Color(0, 102, 102));
        btnHelp.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("CONSULTER L'AIDE");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 310, 196, 40));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BEYOND THE RIVER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 390, 60));

        btnChargerPartie.setBackground(new java.awt.Color(0, 102, 102));
        btnChargerPartie.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        btnChargerPartie.setForeground(new java.awt.Color(255, 255, 255));
        btnChargerPartie.setText("Charger Partie");
        btnChargerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargerPartieActionPerformed(evt);
            }
        });
        getContentPane().add(btnChargerPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 252, 196, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        PlayersInfoFrame pinfo = new PlayersInfoFrame();
        pinfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        HelpMenu hp = new HelpMenu();
        hp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChargerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargerPartieActionPerformed
        Partie partie = null;
        try {
            FileInputStream fichier = new FileInputStream("sauvegarde.bin");
            ObjectInputStream entree = new ObjectInputStream(fichier);
            partie = (Partie) entree.readObject();
            entree.close();
            fichier.close();
            System.out.println("Partie chargée avec succès !");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }

        if (partie != null) {
            PlateauFrame pf = new PlateauFrame(partie.getUser1(), partie.getUser2(), partie.getTotalTurns(), partie.getPlateauLogique());
            
            pf.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnChargerPartieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnChargerPartie;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbSubTitle;
    // End of variables declaration//GEN-END:variables
}
